api/urls.py
from rest_framework import routers
from django.conf.urls import url, include

from .views import (
    AnswerViewSet,
    ContractorResumeFilesViewSet,
    ContractorResumeViewSet,
    DocumentViewSet,
    ElFormatViewSet,
    LocationViewSet,
    LocationViewSetFlat,
    MessageViewSet,
    NoteViewSet,
    OrderViewSet,
    PortfolioPhotoViewSet,
    PortfolioViewSet,
    ProjectViewSet,
    RealtyViewSet,
    UpdateRealty,
    ReviewViewSet,
    BuildingClassificationViewSet,
    SpecializationViewSet,
    SpecializationViewSetFlat,
    ConstructionTypeViewSet,
    StageViewSet,
    StageUpdateViewSet,
    TeamViewSet,
    UserViewSet,
    WorkSellPhotoViewSet,
    WorkSellViewSet,
)

router = routers.DefaultRouter()

router.register(r'answers', AnswerViewSet)
router.register(r'building_classifications', BuildingClassificationViewSet)
router.register(r'construction_type', ConstructionTypeViewSet)
router.register(r'contractorresume', ContractorResumeViewSet)
router.register(r'contractorresumefiles', ContractorResumeFilesViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'el_format', ElFormatViewSet)
router.register(r'locations', LocationViewSet)
router.register(r'locations_flat', LocationViewSetFlat)
router.register(r'message', MessageViewSet, base_name='Message')
router.register(r'note', NoteViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'portfolio-photos', PortfolioPhotoViewSet)
router.register(r'portfolios', PortfolioViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'realties', RealtyViewSet)
router.register(r'reviews', ReviewViewSet)
router.register(r'specializations', SpecializationViewSet)
router.register(r'specializations_flat', SpecializationViewSetFlat)
router.register(r'stages', StageViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'users', UserViewSet)
router.register(r'work-sell-photos', WorkSellPhotoViewSet)
router.register(r'work-sells', WorkSellViewSet)

urlpatterns = router.urls

urlpatterns = [
    url(r'^update_stages/$', StageUpdateViewSet.as_view()),
    # url(r'^orders/(?P<pk>\d+)/$', OrderViewSet.as_view({'delete'})),
]

urlpatterns += router.urls

chat/urls.py
from django.conf import urls

from .views import (
    ChatUserView,
    DocumentCreateView,
    messages_delete,
    project_delete,
    download_file,
)

app_name = 'chat'

urlpatterns = [
    urls.url(r'^$', ChatUserView.as_view(), name='chat-user'),
    urls.url(r'^messages_delete/$', messages_delete, name='chat-messages_delete'),
    urls.url(r'^project/trashed/$', project_delete),
    urls.url(r'^create/$', DocumentCreateView.as_view()),
    urls.url(r'^download/(?P<file_name>.+)', download_file),

]

projects/urls.py
from django.conf import urls

from .views import (
    # ContractorOfferOrder,
    # TeamOfferOrder,
    add_candidate,
    ArbitrationCreateView,
    CandidateDeleteView,
    # contractor_portfolio_create,
    ContractorAnswerArchiveView,
    ContractorPortfolioCreateView,
    ContractorPortfolioTrashView,
    ContractorPortfolioEditView,
    CustomerOfferOrderView,
    CustomerProjectCreateView,
    CustomerProjectDeleteView,
    CustomerProjectEditView,
    CustomerProjectRestoreView,
    CustomerProjectTrashView,
    PortfolioDetail,
    ProjectAnswerCreateMessageView,
    ProjectComparisonView,
    ProjectDetailWithAnswerView,
    ProjectFilterView,
    ProjectWorkTypeSuggestionView,
    RejectProjectAnswerView,
    RestoreProjectAnswerView,
    sort_candidates,
)

app_name = 'projects'

urlpatterns = [
    urls.url(r'^$', ProjectFilterView.as_view(), name='project-filter'),

    # urls.url(r'^create/$', CustomerProjectCreateView.as_view(), name='customer-project-create'),
    urls.url(r'^create$', CustomerProjectCreateView.as_view(), name='customer-project-create'),
    urls.url(r'^(?P<pk>\d+)/$', ProjectDetailWithAnswerView.as_view(), name='detail'),
    urls.url(r'^(?P<pk>\d+)/edit/$', CustomerProjectEditView.as_view(), name='customer-project-edit'),
    urls.url(r'^(?P<pk>\d+)/trash/$', CustomerProjectTrashView.as_view(), name='customer-project-trash'),
    urls.url(r'^(?P<pk>\d+)/restore/$', CustomerProjectRestoreView.as_view(), name='customer-project-restore'),
    urls.url(r'^(?P<pk>\d+)/delete/$', CustomerProjectDeleteView.as_view(), name='customer-project-delete'),

    urls.url(r'^create-answer-message/(?P<pk>\d+)/$', ProjectAnswerCreateMessageView.as_view(),
             name='create-answer-message'),
    urls.url(r'^reject-project-answer/(?P<pk>\d+)/$', RejectProjectAnswerView.as_view(), name='reject-project-answer'),
    urls.url(r'^restore-project-answer/(?P<pk>\d+)/$', RestoreProjectAnswerView.as_view(),
             name='restore-project-answer'),

    urls.url(r'^arbitration/create/$', ArbitrationCreateView.as_view(), name='arbitration-create'),
    urls.url(r'^answer/move/archive/$', ContractorAnswerArchiveView.as_view(), name='contractor-answer-archive'),

    urls.url(r'^portfolio/create/$', ContractorPortfolioCreateView.as_view(), name='contractor-portfolio-create'),
    urls.url(r'^portfolio/(?P<pk>\d+)/$', PortfolioDetail.as_view(), name='contractor-portfolio-detail'),
    urls.url(r'^portfolio/(?P<pk>\d+)/edit/$', ContractorPortfolioEditView.as_view(),
             name='contractor-portfolio-edit'),
    urls.url(r'^portfolio/(?P<pk>\d+)/trash/$', ContractorPortfolioTrashView.as_view(),
             name='contractor-portfolio-trash'),

    urls.url(r'^candidate/add/(?P<answer_id>(\d+))/(?P<project_id>(\d+))/$', add_candidate, name='add-candidate'),
    urls.url(r'^candidate/delete/(?P<pk>(\d+))/$', CandidateDeleteView.as_view(), name='delete-candidate'),
    urls.url(r'^candidate/comparison/sort/$', sort_candidates, name='comparison-sort'),
    urls.url(r'^candidate/comparison/(?P<pk>\d+)/$', ProjectComparisonView.as_view(), name='comparison'),

    urls.url(r'^customer-offer-order/(?P<answer_id>(\d+))/(?P<project_id>(\d+))/$', CustomerOfferOrderView.as_view(),
             name='customer-offer-order'),

    urls.url(r'^suggest-work-type/$', ProjectWorkTypeSuggestionView.as_view(), name='suggest-work-type'),
]

users/urls.py
from django.conf import urls

from .views import (
    AcceptTeamInvitation,
    RefuseTeamInvitation,
    contractor_resumefile_create,
    ContractorChatProjectsView,
    ContractorFilterView,
    ContractorOfficeProjectsView,
    ContractorOfficeView,
    ContractorProfileView,
    ContractorResumeUpdateView,
    CreateTeamInvitation,
    CustomerProfileView,
    CustomerProfileCurrentProjectsView,
    CustomerProfileReviewsView,
    CustomerProfileTrashedProjectsView,
    TeamCreateView,
    TeamProfileView,
    UserProfileEditViewFull,
    dashboard_redirect
)

app_name = 'users'

urlpatterns = [
    urls.url(r'^(?P<pk>\d+)/edit/$', UserProfileEditViewFull.as_view(), name='user-profile-edit'),
    urls.url(r'^dashboard_redirect/$', dashboard_redirect, name='dashboard-redirect'),
    urls.url(r'^customers/(?P<pk>\d+)/$', CustomerProfileView.as_view(),
             name='customer-profile'),
    urls.url(r'^customers/(?P<pk>\d+)/trashed-projects/$', CustomerProfileTrashedProjectsView.as_view(),
             name='customer-profile-trashed-projects'),
    urls.url(r'^customers/(?P<pk>\d+)/current-projects/$', CustomerProfileCurrentProjectsView.as_view(),
             name='customer-profile-current-projects'),
    urls.url(r'^customers/(?P<pk>\d+)/reviews/$', CustomerProfileReviewsView.as_view(),
             name='customer-profile-reviews'),

    urls.url(r'^contractors/$', ContractorFilterView.as_view(), name='contractor-filter'),
    urls.url(r'^contractors/resume/(?P<pk>\d+)/edit/$', ContractorResumeUpdateView.as_view(),
             name='contractor-resume-update'),
    urls.url(r'^contractors/team/create/$', TeamCreateView.as_view(), name='team-create'),
    urls.url(r'^contractorsresumefiles/create/$', contractor_resumefile_create, name='contractor-resume-file-create'),
    urls.url(r'^contractors/(?P<pk>\d+)/$', ContractorProfileView.as_view(), name='contractor-profile'),
    urls.url(r'^contractor-office/$', ContractorOfficeView.as_view(), name='contractor-office'),
    urls.url(r'^contractor-office/open-projects/$', ContractorOfficeProjectsView.as_view(),
             name='contractor-office-open-projects'),
    urls.url(r'^contractor-office/work-projects/$', ContractorChatProjectsView.as_view(),
             name='contractor-office-chat-projects'),

    urls.url(r'^teams/(?P<pk>\d+)/$', TeamProfileView.as_view(), name='team-profile'),

    urls.url(r'^create-team-invitation/(?P<contractor_id>\d+)/$', CreateTeamInvitation.as_view(),
             name='create-team-invitation'),
    urls.url(r'^accept-team-invitation/(?P<owner_id>\d+)/$', AcceptTeamInvitation.as_view(),
             name='accept-team-invitation'),
    urls.url(r'^refuse-team-invitation/(?P<owner_id>\d+)/$', RefuseTeamInvitation.as_view(),
             name='refuse-team-invitation'),
]

wallets/urls.py
from django.conf import urls, settings
from django.views.generic import TemplateView

from .views import PayFromScore, WithDrawCreate, ScoreView

app_name = 'wallets'

urlpatterns = [
    # urls.url(r'^score/(?P<pk>\d+)/$', ScoreDetailView.as_view(), name='score-detail'),
    urls.url(r'^score/(?P<pk>\d+)/$', ScoreView.as_view(), name='score-detail'),
    urls.url(r'^withdraw/create/$', WithDrawCreate.as_view(), name='withdraw-create'),
    urls.url(r'^payfromscore/$', PayFromScore.as_view(), name='payfromscore'),

    urls.url(
        r'^tmp-yamoney-req/$',
        TemplateView.as_view(template_name='tmp_yandex_money_request_example.html'),
        {'YANDEX_MONEY': settings.YANDEX_MONEY},
        name='tmp-yamoney-req',
    ),

    urls.url(
        r'^tmp-yamoney-sim/$',
        TemplateView.as_view(template_name='tmp_yandex_money_responses_sumulation.html'),
        name='tmp-yamoney-sim',
    ),
]

templates/partials/trash/header.html
{% load staticfiles %}
{% load thumbnail %}
{% load user_tags %}
{% load activeurl %}
{% load sass_tags %}
{% load common_tags %}

{% if request.user.is_contractor %}
    {% url 'users:contractor-profile' pk=request.user.pk as profile_url %}
{% elif request.user.is_customer %}
    {% url 'users:customer-profile-open-projects' pk=request.user.pk as profile_url %}
{% endif %}

<link rel='stylesheet' href='{% sass_src "partials/sass/header.sass" %}'>

<div class="wrTop {% if request.user.is_authenticated %} disTab {% endif %}">
    <div class="container-fluid topMain">
        <div class="row">
            <div style="float: left">
                <a href="/">
                    <div class="logo"></div>
                </a>
            </div>

            {% activeurl %}
                <div style="height: 100%; display: inline-block; text-align: center">
                    {% if request.user.is_authenticated %}

                        <ul class="mainMenu">
                            <li class="icon_tm1">
                                <a href="{% url 'projects:project-filter' %}">Поиск заказов</a>
                                <span></span>
                            </li>

                            {% if request.user.is_contractor %}
                                <li class="officeList icon_tml">
                                    <a href="{% url 'users:contractor-office' %}">
                                        Мой офис {% count_new_message_orders request.user %}
                                    </a>
                                    <span></span>
                                </li>
                                <li class="icon_tm3">
                                    <a href="{% url 'work_sell:filter' %}">Готовые проекты</a>
                                    <span></span>
                                </li>
                            {% endif %}

                            {% if request.user.is_customer %}
                                <li class="icon_tm2">
                                    <a href="{% url 'users:contractor-filter' %}">Поиск исполнителей</a>
                                    <span></span>
                                </li>
                                <li class="icon_tm3">
                                    <a href="{% url 'work_sell:filter' %}">Готовые проекты</a>
                                    <span></span>
                                </li>
                            {% endif %}
                        </ul>
                        <div style="clear: both"></div>
                    {% else %}
                        <ul class="mainMenu">
                            <li class="icon_tm1">
                                <a href="{% url 'projects:project-filter' %}">Поиск заказов</a>
                                <span></span>
                            </li>
                            <li class="icon_tm2">
                                <a href="{% url 'users:contractor-filter' %}">Поиск исполнителей</a>
                                <span></span>
                            </li>
                            <li class="icon_tm3">
                                <a href="{% url 'work_sell:filter' %}">Готовые проекты</a>
                                <span></span>
                            </li>
                        </ul>

                    {% endif %}
                </div>
            {% endactiveurl %}
            <div style="float: right">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_contractor %}
                        {% contractor_indicator request.user %}
                    {% endif %}

                    <div class="infoProfile disTab">
                        <div class="btn-group" role="group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                            </button>
                            <ul class="dropdown-menu menu-drop-new">
                                {% if request.user.is_contractor %}
                                    <li class="icon_mm1">
                                        <a href="{% url 'auth_login' %}">
                                            Войти заказчиком
                                            <span></span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="icon_mm2">
                                        <a href="{% url 'auth_login' %}">
                                            Войти исполнителем
                                            <span></span>
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="icon_mm8">
                                    <a href="{{ profile_url }}">
                                        Профиль<span></span>
                                    </a>
                                </li>
                                <li class="icon_chat">
                                    <a href="{% url 'chat:chat-user' %}">Сообщения<span></span></a>
                                    {% if request.user %}
                                        <div class="circle js-all-messages">{{ new_messages_count| max_count:99 }}</div>
                                        {#                                        {% count_new_message request.user %}#}
                                    {% endif %}
                                </li>
                                <li class="icon_mm4">
                                    <a href="{% url 'wallets:score-detail' pk=request.user.pk %}">Счет<span></span></a>
                                </li>
                                <li class="icon_mm5">
                                    <a href="{% url 'users:user-profile-edit' pk=request.user.pk %}">Настройки<span></span></a>
                                </li>

                                <li class="icon_mm6">
                                    <a href="/pages/faq">FAQ<span></span></a>
                                </li>
                                {% if request.user.is_contractor %}
                                    <li class="icon_mm2">
                                        <a href="{% url 'auth_logout' %}">Выйти<span></span></a>
                                    </li>
                                {% else %}
                                    <li class="icon_mm7">
                                        <a href="{% url 'auth_logout' %}">Выйти<span></span></a>
                                    </li>
                                {% endif %}

                            </ul>
                        </div>
                    </div>
                    <div class="imgProfile">
                        {% if request.user.is_contractor %}
                            <a href="{{ profile_url }}">
                                {% if request.user.avatar %}
                                    {% thumbnail request.user.avatar "75x75" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="profile-image">
                                    {% endthumbnail %}
                                {% else %}
                                    {% if request.user.gender == "female" %}
                                        <img src="{% static 'img/avatars/avatar-female.jpg' %}" alt="profile-image">
                                    {% else %}
                                        <img src="{% static 'img/avatars/avatar-male.jpg' %}" alt="profile-image">
                                    {% endif %}
                                {% endif %}
                            </a>
                        {% elif request.user.is_customer %}
                            <a href="{{ profile_url }}">
                                {% if request.user.avatar %}
                                    {% thumbnail request.user.avatar "75x75" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="profile-image">
                                    {% endthumbnail %}
                                {% else %}
                                    {% if request.user.gender == "female" %}
                                        <img src="{% static 'img/avatars/avatar-female.jpg' %}" alt="profile-image">
                                    {% else %}
                                        <img src="{% static 'img/avatars/avatar-male.jpg' %}" alt="profile-image">
                                    {% endif %}
                                {% endif %}
                            </a>
                        {% endif %}
                    </div>
                    {% if request.user.is_contractor %}
                        <div class="user-info">
                            <a href="{% url 'wallets:score-detail' pk=request.user.pk %}"
                               class="cash">{{ user_balance|floatformat:2 }}р</a>
                            <a href="{% url 'chat:chat-user' %}#order{{ fist_order_id }}"
                               class="icon_hand">{{ num_orders_in_work }}</a>
                            <a href="{% url 'chat:chat-user' %}" class="icon_chat js-all-messages">
                                {{ new_messages_count| max_count:99 }}
                            </a>
                        </div>
                    {% endif %}

                {% else %}
                    <a href="{% url 'registration_register' %}" class="reg">Регистрация</a>
                    <a href="{% url 'auth_login' %}">
                        <div class="lock"></div>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>