api/urls.py
from rest_framework import routers
from django.conf.urls import url, include

from .views import (
    AnswerViewSet,
    ContractorResumeFilesViewSet,
    ContractorResumeViewSet,
    DocumentViewSet,
    ElFormatViewSet,
    LocationViewSet,
    LocationViewSetFlat,
    MessageViewSet,
    NoteViewSet,
    OrderViewSet,
    PortfolioPhotoViewSet,
    PortfolioViewSet,
    ProjectViewSet,
    RealtyViewSet,
    UpdateRealty,
    ReviewViewSet,
    BuildingClassificationViewSet,
    SpecializationViewSet,
    SpecializationViewSetFlat,
    ConstructionTypeViewSet,
    StageViewSet,
    StageUpdateViewSet,
    TeamViewSet,
    UserViewSet,
    WorkSellPhotoViewSet,
    WorkSellViewSet,
)

router = routers.DefaultRouter()

router.register(r'answers', AnswerViewSet)
router.register(r'building_classifications', BuildingClassificationViewSet)
router.register(r'construction_type', ConstructionTypeViewSet)
router.register(r'contractorresume', ContractorResumeViewSet)
router.register(r'contractorresumefiles', ContractorResumeFilesViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'el_format', ElFormatViewSet)
router.register(r'locations', LocationViewSet)
router.register(r'locations_flat', LocationViewSetFlat)
router.register(r'message', MessageViewSet, base_name='Message')
router.register(r'note', NoteViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'portfolio-photos', PortfolioPhotoViewSet)
router.register(r'portfolios', PortfolioViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'realties', RealtyViewSet)
router.register(r'reviews', ReviewViewSet)
router.register(r'specializations', SpecializationViewSet)
router.register(r'specializations_flat', SpecializationViewSetFlat)
router.register(r'stages', StageViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'users', UserViewSet)
router.register(r'work-sell-photos', WorkSellPhotoViewSet)
router.register(r'work-sells', WorkSellViewSet)

urlpatterns = router.urls

urlpatterns = [
    url(r'^update_stages/$', StageUpdateViewSet.as_view()),
    # url(r'^orders/(?P<pk>\d+)/$', OrderViewSet.as_view({'delete'})),
]

urlpatterns += router.urls

wallets/urls.py
from django.conf import urls, settings
from django.views.generic import TemplateView

from .views import PayFromScore, WithDrawCreate, ScoreView

app_name = 'wallets'

urlpatterns = [
    # urls.url(r'^score/(?P<pk>\d+)/$', ScoreDetailView.as_view(), name='score-detail'),
    urls.url(r'^score/(?P<pk>\d+)/$', ScoreView.as_view(), name='score-detail'),
    urls.url(r'^withdraw/create/$', WithDrawCreate.as_view(), name='withdraw-create'),
    urls.url(r'^payfromscore/$', PayFromScore.as_view(), name='payfromscore'),

    urls.url(
        r'^tmp-yamoney-req/$',
        TemplateView.as_view(template_name='tmp_yandex_money_request_example.html'),
        {'YANDEX_MONEY': settings.YANDEX_MONEY},
        name='tmp-yamoney-req',
    ),

    urls.url(
        r'^tmp-yamoney-sim/$',
        TemplateView.as_view(template_name='tmp_yandex_money_responses_sumulation.html'),
        name='tmp-yamoney-sim',
    ),
]

wallets/forms.py
from django import forms
from django.conf import settings

from .models import WithDraw, PayFromScore


class WithDrawForm(forms.ModelForm):
    class Meta:
        model = WithDraw

        fields = (
            'passport',
            'phone',
            'sum',
            'user',
            'yandex_card',
        )


class PayFromScoreForm(forms.ModelForm):
    class Meta:
        model = PayFromScore

        fields = (
            'sum',
            'stages_id',
        )


class TmpCheckOrderForm(forms.Form):
    action = forms.CharField()  # Has to be "checkOrder"
    md5 = forms.CharField()
    shopId = forms.IntegerField()
    invoiceId = forms.IntegerField()

    def clean_action(self):
        action = self.cleaned_data.get('action')

        if action != 'checkOrder':
            raise forms.ValidationError('Wrong action')

        return action

    def clean_shopId(self):
        shopId = self.cleaned_data.get('shopId')

        if shopId != settings.YANDEX_MONEY['shop_id']:
            raise forms.ValidationError('Wrong shop ID')

        return shopId


class TmpPaymentAvisoForm(forms.Form):
    action = forms.CharField()  # Has to be "paymentAviso"
    md5 = forms.CharField()
    shopId = forms.IntegerField()
    invoiceId = forms.IntegerField()
    orderSumAmount = forms.DecimalField()

    def clean_action(self):
        action = self.cleaned_data.get('action')

        if action != 'paymentAviso':
            raise forms.ValidationError('Wrong action')

        return action

    def clean_shopId(self):
        shopId = self.cleaned_data.get('shopId')

        if shopId != settings.YANDEX_MONEY['shop_id']:
            raise forms.ValidationError('Wrong shop ID')

        return shopId

wallets/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, CreateView
from django.views.generic.base import View

from projects.models import Stage
from users.models import User
from .forms import WithDrawForm, TmpCheckOrderForm, TmpPaymentAvisoForm, PayFromScoreForm
from .models import InvoiceHistory, WithDraw, Transaction, PayFromScore
from .signals import *


class PayFromScore(CreateView):
    model = PayFromScore
    form_class = PayFromScoreForm

    def form_valid(self, form):
        if self.request.is_ajax():
            # print("self.request.user.get_score()", self.request.user.get_score(), ">= form.cleaned_data.get('sum')", form.cleaned_data.get('sum'))
            if self.request.user.get_score() >= form.cleaned_data.get('sum'):
                # print("stages_id = ", form.cleaned_data.get('stages_id'), type(form.cleaned_data.get('stages_id')))
                stages_pk = [st for st in form.cleaned_data.get('stages_id').split(';') if st]
                # print("stages_pk = ", stages_pk)
                stages = Stage.objects.filter(pk__in=stages_pk)
                st_names = ','.join([st.order.project.name for st in stages]).rstrip(',')
                stage = stages.first()
                # stage.is_paid = True
                # stage.save()
                order = stage.order
                self.object = form.save(commit=False)
                self.object.customer = self.request.user
                self.object.save()
                data = {
                    'pk': self.object.pk,
                    'status': 'ok',
                    'order': order.pk,
                    'sender': self.request.user.pk,
                    'recipent': order.get_contractor_owner(),
                    'stages': st_names,
                }
                return JsonResponse(data)
            else:
                data = {
                    'status': 'error',
                    'message_error': 'У вас недостаточно средств',
                }
                return JsonResponse(data, status=400)
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.is_ajax():
            data = {
                'errors': form.errors,
                'status': 'error',
            }
            return JsonResponse(data)
        return super().form_invalid(form)


class ScoreDetailView(DetailView):
    model = User
    template_name = 'score-detail.html'
    context_object_name = 'user_score'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_score_balance = InvoiceHistory.objects.filter(user=self.get_object()).aggregate(Sum('sum'))
        context['user_score_balance'] = user_score_balance['sum__sum'] or 0
        context['form'] = WithDrawForm()
        return context


class ScoreView(LoginRequiredMixin, View):
    template_name = 'score-detail.html'

    def get(self, request, *args, **kwargs):
        transaction, created = Transaction.objects.get_or_create(customer=request.user, type='add', complete=False)
        # transaction = Transaction.objects.filter(customer=request.user, type='add', complete=False)
        user_score = get_object_or_404(User.objects, pk=kwargs.get('pk'))
        current_sum_info = InvoiceHistory.objects.filter(user=user_score, type="score").aggregate(Sum('sum'))
        user_score_balance = current_sum_info['sum__sum'] or 0
        form = WithDrawForm

        return render(request, self.template_name, {
            'transaction': transaction,
            'YANDEX_MONEY': settings.YANDEX_MONEY,
            'user_score': user_score,
            'user_score_balance': user_score_balance,
            'form': form,
        })


class AjaxableResponseMixin(object):
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # import code; code.interact(local=dict(globals(), **locals()))
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            messages.info(self.request, 'Ваша заявка на вывод средств принята!')
            data = {
                'pk': self.object.pk,
                'status': 'ok',
            }
            return JsonResponse(data)
        else:
            return response


class WithDrawCreate(CreateView):
    model = WithDraw
    form_class = WithDrawForm

    def form_valid(self, form):
        if self.request.is_ajax():
            self.object = form.save()
            messages.info(self.request, 'Ваша заявка на вывод средств принята!')
            data = {
                'pk': self.object.pk,
                'status': 'ok',
            }
            return JsonResponse(data)
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.is_ajax():
            data = {
                'errors': form.errors,
                'status': 'error',
            }
            return JsonResponse(data)
        return super().form_invalid(form)


# Yandex Money ------------------------------------------------



class TmpCheckOrderView(View):
    form_class = TmpCheckOrderForm

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logging.debug('###############################################')
        logging.debug('TmpCheckOrderView')
        logging.debug('###############################################')

        form = self.form_class(request.POST)

        # trans = form.cleaned_data.get('transaction')

        if form.is_valid():
            res = """<?xml version="1.0" encoding="utf-8"?>
                <checkOrderResponse
                    performedDatetime="{date}"
                    code="0"
                    invoiceId="{invoice_id}"
                    shopId="{shop_id}"/>
            """.format(
                date=timezone.now().isoformat(),
                invoice_id=form.cleaned_data.get('invoiceId'),
                shop_id=form.cleaned_data.get('shopId'),
            )

            return HttpResponse(res, content_type='application/xml')
        else:
            res = """<?xml version="1.0" encoding="utf-8"?>
                <checkOrderResponse
                    performedDatetime="{date}"
                    code="1"
                    invoiceId="{invoice_id}"
                    shopId="{shop_id}"
                    message="Check order, validation error"
                    techMessage="Check order, validation error"/>
            """.format(
                date=timezone.now().isoformat(),
                invoice_id=form.cleaned_data.get('invoiceId'),
                shop_id=form.cleaned_data.get('shopId'),
            )

            return HttpResponse(res, content_type='application/xml')
            # return HttpResponse('<pre>{msg}</pre>'.format(msg=pformat(form.errors))) # Debug


class TmpPaymentAvisoView(View):
    form_class = TmpPaymentAvisoForm

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        logging.debug(form.data)
        if form.is_valid():
            transaction_id = form.data.get('transactionId')
            transaction = Transaction.objects.get(pk=int(transaction_id))
            logging.debug(form.cleaned_data)
            transaction.complete = True
            transaction.sum = form.cleaned_data.get('orderSumAmount')
            transaction.stages_id = form.data.get('stagesId')
            transaction.save()

            res = """<?xml version="1.0" encoding="utf-8"?>
                <paymentAvisoResponse
                    performedDatetime="{date}"
                    code="0"
                    invoiceId="{invoice_id}"
                    shopId="{shop_id}"/>
            """.format(
                date=timezone.now().isoformat(),
                invoice_id=form.cleaned_data.get('invoiceId'),
                shop_id=form.cleaned_data.get('shopId'),
            )

            return HttpResponse(res, content_type='application/xml')
        else:
            res = """<?xml version="1.0" encoding="utf-8"?>
                <paymentAvisoResponse
                    performedDatetime="{date}"
                    code="1"
                    message="Payment aviso, validation error"
                    techMessage="Payment aviso, validation error"/>
            """.format(date=timezone.now().isoformat())

            return HttpResponse(res, content_type='application/xml')
            # return HttpResponse('<pre>{msg}</pre>'.format(msg=pformat(form.errors))) # Debug

wallets/templates/score-detail.html
{% extends 'partials/base.html' %}

{% load staticfiles %}
{% load thumbnail %}

{% block head_css %}
    <style>
        @media print {
            footer, button, a, p, .wrTop, .titleScore, .triangle1 {
                display: none !important;
            }

            .row {
                border: 0 !important;
            }

            .col-lg-12 {
                padding: 0;
            }

            .scoreButtons table {
               width: 94% !important;
            }
        }
    </style>
{% endblock %}

{% block content %}


    {% include 'partials/header.html' %}
    <div class="container mainScore">
        <div class="row">
            <div class="col-lg-12">
                <p class="titleScore">Ваш счет</p>
            </div>
            <div class="col-lg-12">
                <div class="scoreButtons disTab">
                    <div class="triangle1"></div>
                    <p>{{ user_score_balance }} <i class="fa fa-rub"></i></p>

                    {% if user_score.is_customer %}
                        <div class="col-lg-12">
                            <a href="#" data-toggle="modal" data-target="#fullfill-balance" class="linkS linkS1">пополнить</a>
                        </div>
                    {% endif %}


                    {% if user_score.is_contractor  %}
                        <div class="col-lg-12">
                            <a href="#" data-toggle="modal" data-target="#withdraw-money" class="linkS linkS2">вывести средства</a>
                        </div>
                    {% endif %}

                    <div id="withdraw-money" class="modal fade" role="dialog">
                        <div class="modal-dialog" role="document" style="width:900px;">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
                                    </button>
                                    <h4 class="modal-title">Вывод денег</h4>
                                </div>
                                <form id="withdraw-form" action="{% url 'wallets:withdraw-create' %}" method="POST">{% csrf_token %}
                                <div class="modal-body">
                                    <div style="height: 150px;">
                                    <div class="textAreaBlock2 text-nn box-sizing disTab">
                                        <p>Кол-во денег<span style="color: red; margin-left:8px; font-size: 12px;"
                             class="error-{{ form.sum.html_name }}"></span> </p>
                                        <input type="text" name="{{ form.sum.html_name }}">
                                    </div>

                                    <div class="textAreaBlock2 text-nn box-sizing disTab">
                                        <p>Номер Яндекс кошелька <span style="color: red; margin-left:8px; font-size: 12px;"
                             class="error-{{ form.yandex_card.html_name }}"></span> </p>
                                        <input type="text" name="{{ form.yandex_card.html_name }}">
                                        <input type="hidden" name="{{ form.user.html_name }}" value="{{ user_score.pk }}">
                                    </div>

                                    <div class="textAreaBlock2 text-nn box-sizing disTab">
                                        <p>Телефон <span style="color: red; margin-left:8px; font-size: 12px;" class="error-{{ form.phone.html_name }}"></span></p>
                                        <input type="text" name="{{ form.phone.html_name }}">
                                    </div>

                                    <div class="textAreaBlock2 text-nn box-sizing disTab">
                                        <p>Номер паспорта <span style="color: red; margin-left:8px; font-size: 12px;" class="error-{{ form.passport.html_name }}"></span></p>
                                        <input type="text" name="{{ form.passport.html_name }}">
                                    </div>
                                    
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                                    <button type="submit" class="btn btn-primary">Вывести</button>
                                </div>
                                </form>

                            </div>
                        </div>
                    </div>

                    <div id="fullfill-balance" class="modal fade" role="dialog">
                        <div class="modal-dialog" role="document" style="width:900px;">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
                                    </button>
                                    <h4 class="modal-title">Пополнить счет</h4>
                                </div>
                                <form id="withdraw-form" action="{{ YANDEX_MONEY.url }}" method="POST">{% csrf_token %}
                                <div class="modal-body">
                                    <div style="height: 150px;">
                                    <div class="textAreaBlock2 text-nn box-sizing disTab">
                                        <p>Кол-во денег</p>
                                        <input type="text" name="sum">
                                        
                                        <input type='hidden' name='shopId' value='{{ YANDEX_MONEY.shop_id }}'>
                                        <input type='hidden' name='scid' value='{{ YANDEX_MONEY.scid }}'>
                                        <input type='hidden' name='customerNumber' value='{{ user_score.pk }}'>
                                        <input type='hidden' name='paymentType' value='AC'>
                                        <input type='hidden' name='transactionId' value='{{ transaction.pk }}'>
                                    </div>
                                        
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                                    <button type="submit" class="btn btn-primary">Пополнить</button>
                                </div>
                                </form>

                            </div>
                        </div>
                    </div>

                    <button type="button"  class="print-score btn-submit-link"
                            style="margin-bottom: 15px !important"
                            onClick="window.print()">Распечатать</button>
                    <table>
                        <tr>
                            <th>Дата</th>
                            <th>Описание</th>

                            <th>Поступление/Списание</th>
                            <th>Баланс</th>
                        </tr>
                        {% for history in user_score.invoice_history.all %}
                            <tr>
                                <td>{{ history.created }}</td>
                                <td>
                                    {{ history.comment }}
                                </td>

                                <td>
                                    {{ history.sum }}
                                    <i class="fa fa-rub"></i>
                                </td>
                                <td>
                                    {{ history.balance }}
                                    <i class="fa fa-rub"></i>
                                </td>
                            </tr>
                        {% empty %}
                          <tr>
                          <td colspan="4">
                            Платежей и/или списаний пока нет
                          </td>
                          </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
            {% include 'partials/footer.html' %}
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script type="text/javascript">

        $(function () {
            $('#withdraw-form').on('submit', function (e) {
                e.preventDefault();
                var dataSerializer = $(this).serialize()
                $.ajax({
                    url: '/wallets/withdraw/create/',
                    method: 'POST',
                    data: dataSerializer,
                    dataType: 'json',
                    success: function (data) {
                        console.log(data);

                        if (data.status == 'ok') {
                            location.reload();
                        }else if (data.status == 'error'){
                            $.each(data.errors, function (k, v) {
                                if (k == '__all__'){
                                   $('.error-sum').html(v).show();
                                }
                                $('.error-' + k).html(v).show();
                            });
                        }
                    },
                    error: function (jqXHR, exception) {
                        console.log(jqXHR);
                        console.log(exception);
                        console.log(jqXHR.statusCode);
                    }

                })
            });
        });

    </script>
{% endblock %}

wallets/templates/score-test.html
<h1> Ваш счет: {{ score }}</h1>

wallets/templates/send_for_accountant.html
Заявка на вывод средств от {{ username }}!

wallets/templates/tmp_yandex_money_request_example.html
{% extends 'partials/base.html' %}

{% block content %}
    <div class='container-fluid'>
        <div class='row'>
            <div class='a col-xs-12'>
                <form action='{{ YANDEX_MONEY.url }}' method='POST' novalidate>
                    <p>shopId: <input type='text' name='shopId' value='{{ YANDEX_MONEY.shop_id }}'></p>
                    <p>scid: <input type='text' name='scid' value='{{ YANDEX_MONEY.scid }}'></p>
                    <p>sum: <input type='text' name='sum' value='100'></p>
                    <p>customerNumber: <input type='text' name='customerNumber' value='123'></p>
                    
                    <p>transactionId: <input type='text' name='transactionId' value='{{ transaction.pk }}'></p>
                    
                    <p><button type='submit'>Simulate check</button></p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

wallets/templates/tmp_yandex_money_responses_sumulation.html
{% extends 'partials/base.html' %}

{% block content %}
    <div class='container-fluid'>
        <div class='row'>
            <div class='a col-xs-12'>
                <h3>Simulating a Yandex "checkOrder" request</h3>
                
                <form action='{% url 'tmp-check-order' %}' method='POST' novalidate>
                    <p>action: <input name='action' value='checkOrder'></p>
                    <p>md5: <input name='md5' value='8256D2A032A35709EAF156270C9EFE2E'></p>
                    <p>shopId: <input name='shopId' value='59838'></p>
                    <p>invoiceId: <input name='invoiceId' value='1234567'></p>
                    <p>customerNumber: <input name='customerNumber' value='8123294469'></p>
                    <p>orderSumAmount: <input name='orderSumAmount' value='87.1'></p>
                    <p>orderSumCurrencyPaycash: <input name='orderSumCurrencyPaycash' value='643'></p>
                    <p>orderSumBankPaycash: <input name='orderSumBankPaycash' value='1001'></p>
                    <p>shopPassword: <input name='shopPassword' value='x1uvmS9Iq8WBE3Oo'></p>
                    
                    <p>orderNumber: <input name='orderNumber' value='123'></p>
                    
                    <p><button type='submit'>Simulate check</button></p>
                </form>
            </div>
        </div>
        
        
        
        
        
        
        <div class='row'>
            <div class='b col-xs-12'>
                <h3>Simulating a Yandex "paymentAviso" request</h3>
                
                <form action='{% url 'tmp-payment-aviso' %}' method='POST' novalidate>
                    <p>action: <input name='action' value='paymentAviso'></p>
                    <p>md5: <input name='md5' value='45125C95A20A7F25B63D58EA304AFED2'></p>
                    <p>shopId: <input name='shopId' value='59838'></p>
                    <p>invoiceId: <input name='invoiceId' value='1234567'></p>
                    <p>customerNumber: <input name='customerNumber' value='8123294469'></p>
                    <p>orderSumAmount: <input name='orderSumAmount' value='87.1'></p>
                    <p>orderSumCurrencyPaycash: <input name='orderSumCurrencyPaycash' value='643'></p>
                    <p>orderSumBankPaycash: <input name='orderSumBankPaycash' value='1001'></p>
                    <p>shopPassword: <input name='shopPassword' value='x1uvmS9Iq8WBE3Oo'></p>
                    
                    <p>transactionId: <input name='transactionId' value='1'></p>
                    
                    <p><button type='submit'>Simulate aviso</button></p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}