api/urls.py
from rest_framework import routers
from django.conf.urls import url, include

from .views import (
    AnswerViewSet,
    ContractorResumeFilesViewSet,
    ContractorResumeViewSet,
    DocumentViewSet,
    ElFormatViewSet,
    LocationViewSet,
    LocationViewSetFlat,
    MessageViewSet,
    NoteViewSet,
    OrderViewSet,
    PortfolioPhotoViewSet,
    PortfolioViewSet,
    ProjectViewSet,
    RealtyViewSet,
    UpdateRealty,
    ReviewViewSet,
    BuildingClassificationViewSet,
    SpecializationViewSet,
    SpecializationViewSetFlat,
    ConstructionTypeViewSet,
    StageViewSet,
    StageUpdateViewSet,
    TeamViewSet,
    UserViewSet,
    WorkSellPhotoViewSet,
    WorkSellViewSet,
)

router = routers.DefaultRouter()

router.register(r'answers', AnswerViewSet)
router.register(r'building_classifications', BuildingClassificationViewSet)
router.register(r'construction_type', ConstructionTypeViewSet)
router.register(r'contractorresume', ContractorResumeViewSet)
router.register(r'contractorresumefiles', ContractorResumeFilesViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'el_format', ElFormatViewSet)
router.register(r'locations', LocationViewSet)
router.register(r'locations_flat', LocationViewSetFlat)
router.register(r'message', MessageViewSet, base_name='Message')
router.register(r'note', NoteViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'portfolio-photos', PortfolioPhotoViewSet)
router.register(r'portfolios', PortfolioViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'realties', RealtyViewSet)
router.register(r'reviews', ReviewViewSet)
router.register(r'specializations', SpecializationViewSet)
router.register(r'specializations_flat', SpecializationViewSetFlat)
router.register(r'stages', StageViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'users', UserViewSet)
router.register(r'work-sell-photos', WorkSellPhotoViewSet)
router.register(r'work-sells', WorkSellViewSet)

urlpatterns = router.urls

urlpatterns = [
    url(r'^update_stages/$', StageUpdateViewSet.as_view()),
    # url(r'^orders/(?P<pk>\d+)/$', OrderViewSet.as_view({'delete'})),
]

urlpatterns += router.urls

reviews/urls.py
from django.conf import urls

from .views import ReviewsView, ReviewCreateView

app_name = 'reviews'

urlpatterns = [
    urls.url(r'^$', ReviewsView.as_view(), name='list'),
    urls.url(r'^create/$', ReviewCreateView.as_view(), name='create'),

]

work_sell/urls.py
from django.conf import urls

from .views import (
    WorkSellDetail,
    WorkSellUpdateView,
    WorkSellDeleteView,
    UploadView,
    # work_sell_create,
    WorkSellCreateView,
    BasicCreateView,
    PictureCreateView,
    ContractorWorkSellTrashView,
    WorkSellFilterView,

)

app_name = 'work_sell'

urlpatterns = [
    urls.url(r'^$', WorkSellFilterView.as_view(), name='filter'),
    urls.url(r'^create/$', WorkSellCreateView.as_view(), name='create'),
    urls.url(r'^upload/$', UploadView.as_view(), name='upload'),
    urls.url(r'^(?P<pk>\d+)/edit/$', WorkSellUpdateView.as_view(), name='edit'),
    urls.url(r'^(?P<pk>\d+)/delete/$', WorkSellDeleteView.as_view(), name='delete'),
    urls.url(r'^(?P<pk>\d+)/trash/$', ContractorWorkSellTrashView.as_view(), name='contractor-worksell-trash'),
    # urls.url(r'^create/$', work_sell_create, name='create'),
    urls.url(r'^basic/$', BasicCreateView.as_view(), name='upload-basic'),
    urls.url(r'^new/$', PictureCreateView.as_view(), name='upload-new'),
    urls.url(r'^(?P<pk>\d+)/$', WorkSellDetail.as_view(), name='detail'),
]

work_sell/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from common.models import LiveImageUpload
from projects.models import BuildingClassfication
from specializations.models import Specialization
from .models import WorkSell, WorkSellPhoto


class ContractorWorkSellTrashForm(forms.Form):
    pk = forms.ModelChoiceField(queryset=WorkSell.objects.none())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

        self.fields['pk'].queryset = self.request.user.work_sell.all()


class WorkSellForm(forms.ModelForm):

    class Meta:
        model = WorkSell

        fields = (
            'building_classification',
            'construction_type',
            'specialization',
            'specializations',
            'contractor',
            'location',
            'budget',
            'currency',
            'description',
            'el_format',
            'name',
            'term',
            'term_type',
            # 'photos'
        )

    # def clean(self):
    #     print("CLEAN", self.cleaned_data)
    #     data = self.cleaned_data.get('specializations')
    #     print("before data = ", data)
    #     # print('spec = ', data.split(','))
    #     # self.cleaned_data['specialization'] = data.split(',')
    #     super().clean()

    # def clean_specializations(self):
    #     data = self.cleaned_data['specializations']
    #     print("before data = ", data)
    #     # data = data.split(',')
    #     print("after data = ", data)
    #     return data

    def __init__(self, *args, **kwargs):
        try:
            self.request = kwargs.pop('request')
        except KeyError:
            pass
        super().__init__(*args, **kwargs)
        self.fields['specializations'].required = True
        self.fields['description'].required = True
        # self.fields['photos'].queryset = self.instance.photos.all()


class WorkSellFilterForm(forms.ModelForm):
    keywords = forms.CharField(required=False, max_length=255)

    class Meta:
        model = WorkSell
        fields = (
            'location',
            'building_classification',
            'construction_type',
            'specialization',
        )

        widgets = {
            'building_classification': forms.Select(attrs={'class': 'selectpicker'}),
            'construction_type': forms.Select(attrs={'class': 'selectpicker'}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

        self.fields['specialization'].required = False

        self.fields['specialization'].queryset = Specialization.objects.root_nodes()[0].get_descendants()

work_sell/views.py
import json
import re

import pydash as _;

_.map = _.map_;
_.filter = _.filter_
from pprint import pformat
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from django.core.files.base import ContentFile
from django.views.generic import ListView, DetailView, CreateView, View, \
    UpdateView, DeleteView, TemplateView

from projects.models import BuildingClassfication, ConstructionType
from projects.forms import ProjectWorkTypeSuggestionForm
from archilance.mixins import BaseMixin
from common.forms import CustomRegistrationForm
from users.models import User
from .models import WorkSell, Picture, WorkSellPhoto, WorkSellPhoto
from .forms import WorkSellForm, WorkSellFilterForm, ContractorWorkSellTrashForm
from .serialize import serialize
from .response import JSONResponse, response_mimetype
from specializations.models import Specialization
from common.models import Location
from archilance import util

class PictureCreateView(CreateView):
    model = Picture
    fields = '__all__'

    def form_valid(self, form):
        self.object = form.save()
        files = [serialize(self.object)]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
        return HttpResponse(content=data, status=400, content_type='application/json')


class BasicCreateView(PictureCreateView):
    template_name = 'picture_basic_form.html'


class WorkSellsView(ListView):
    model = WorkSell
    template_name = 'worksells_list.html'
    # paginate_by = 20
    paginate_by = 18

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs

    def get_queryset(self, **kwargs):
        qs = WorkSell.objects.all()
        # if self.request.GET:
        #     budget_from = self.request.GET
        #     pass
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['building_classifications'] = BuildingClassfication.objects.all()
        context['construction_types'] = ConstructionType.objects.all()
        return context


class WorkSellFilterView(BaseMixin, View):
    template_name = 'worksell_filter.html'
    # form_class = WorkSellFilterForm
    include_template = 'partials/inc-worksell-results.html'
    PROJECT_ORDER_CHOICES = (  # "Упорядочить по"...
        ('name', 'названию'),
        ('budget', 'цене'),
    )

    def set_filter(self, objects, request_data):
        specialization = request_data.get('specialization')
        keywords = request_data.get('keywords')
        building_classification = request_data.get('building_classification')
        construction_type = request_data.get('construction_type')
        location = request_data.get('location')
        el_format = request_data.get('el_format')

        if keywords:
            keywords = tuple(filter(None, re.split(r'\s|,|;', keywords)))

            for k in keywords:
                objects = objects.filter(Q(name__icontains=k.lower()) | Q(description__icontains=k.lower()))

        if specialization:
            query = util.build_query(specialization, Specialization,
                                     'specializations__lft__gte',
                                     'specializations__rght__lte')
            objects = objects.filter(query)

        if building_classification:
            query = util.build_query(building_classification, BuildingClassfication,
                                     'building_classification__lft__gte',
                                     'building_classification__rght__lte')
            objects = objects.filter(query)
        #
        if construction_type:
            objects = objects.filter(construction_type__in=
                                       tuple(filter(None, re.split(r'\s|,|;', construction_type))))
        if location:
            query = util.build_query(location, Location,
                                     'location__lft__gte',
                                     'location__rght__lte')
            objects = objects.filter(query)

        if el_format:
            objects = objects.exclude(el_format=None)

        return objects

    def sort_by(self, objects, order_by):
        if not order_by:
            return objects
        return objects.order_by(order_by)

    def pagination(self, objects, page):
        paginator = Paginator(objects, settings.PAGE_SIZE)
        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)
        return objects

    def get_context(self, request):
        context = request.dict()

        worksells = WorkSell.objects.all()
        worksells = self.set_filter(worksells, request)
        num_results = worksells.count()
        worksells = self.sort_by(worksells, request.get("order_by"))
        worksells = self.pagination(worksells, request.get("page"))

        has_additional_fields = bool(context.get("building_classification") or context.get(
            "construction_type") or context.get("location") or context.get("cro"))
        display_msg = 'Найдено %s проектов' % num_results if num_results > 0 else 'Ничего не найдено'
        context.update({
            'choices': self.PROJECT_ORDER_CHOICES,
            'worksells': worksells,
            'is_paginated': True,
            'display_msg': display_msg,
            'page_obj': worksells,
            'has_additional_fields': has_additional_fields
        })
        return context

    def get(self, request):
        return render(request, self.template_name, self.get_context(request.GET))

    def post(self, request):
        return render(request, self.include_template, self.get_context(request.POST))


class WorkSellDetail(DetailView):
    model = WorkSell
    template_name = 'worksell_detail.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.get_object().contractor and not self.get_object().team:
            return HttpResponseForbidden('404 Not Found')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Своя собственная Работа
        self_worksell = False
        try:
            if self.get_object().id in [obj.id for obj in self.request.user.work_sell.all()]:
                self_worksell = True
        except AttributeError:
            pass

        context['worksell_related'] = WorkSell.objects.exclude(pk=self.get_object().pk)[:5]
        context['self_worksell'] = self_worksell
        return context


class WorkSellCreateView(BaseMixin, View):
    model = WorkSell
    form_class = WorkSellForm
    work_type_suggestion_form = ProjectWorkTypeSuggestionForm
    template_name = 'worksell_create.html'

    # Пускаем всех, т.к. незарегистрированный пользователь должен иметь возможность "Создать проект"
    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated() and request.user.is_contractor():
    #         return super().dispatch(request, *args, **kwargs)
    #     else:
    #         raise PermissionDenied

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data()
        user_form = CustomRegistrationForm()
        ctx['user_form'] = user_form
        return ctx

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**_.merge({}, request.GET, kwargs))

        form = self.form_class(request=request)
        work_type_suggestion_form = self.work_type_suggestion_form(request=request, prefix='work_type_suggestion')

        context.update({
            'form': form,
            'work_type_suggestion_form': work_type_suggestion_form,
        })

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # print("request.POST = ", request.POST)
        # print("files = ", request.FILES.getlist('new_files'))
        request.POST = request.POST.copy()
        # Если фронт не будет возвращать пустую строку при незаполненных данных, то if'ы будут не нужны
        if request.POST.get('specializations') == "":
            print("POP")
            request.POST.pop('specializations')
        else:
            request.POST.setlist('specializations', request.POST.get('specializations', "").split(','))

        if request.POST.get('el_format') == "":
            request.POST.pop('el_format')
        else:
            request.POST.setlist('el_format', request.POST.get('el_format', "").split(','))
        form = self.form_class(request.POST, request=request)
        if form.is_valid():
            work_sell = form.save(commit=False)
            unregister_user = request.POST.get('not_auth_user_id')
            if unregister_user:
                user = get_object_or_404(User, pk=unregister_user)
            else:
                user = request.user
            work_sell.contractor = user
            work_sell.save()
            form.save_m2m()

            for file, desc in zip(request.FILES.getlist('new_files'), request.POST.getlist('img_description')):
                WorkSellPhoto.objects.create(img=file, description=desc, worksell=work_sell)

            redirect_to = reverse('work_sell:detail', kwargs={'pk': work_sell.pk})
            if request.is_ajax():
                return JsonResponse({'redirect_to': redirect_to}, status=200)

work_sell/templates/trash/worksells_list.html
{% extends 'partials/base.html' %}

{% load staticfiles %}
{% load thumbnail %}
{% block content %}


{% include 'partials/header.html' %}
    <div class="container mainScore">
        <div class="row">
            <div class="col-lg-12">
                <p class="titleScore">Работы на продажу</p>
            </div>
            
            
               <form action="{% url 'work_sell:list' %}" method="GET" novalidate>
                <div class="col-lg-12">
                    <div class="filter clearfix">
                        <div class="triangle1"></div>

                        <div class="titleF1 disTab">
                            <div class="col-lg-3">Специализации</div>
                            <div class="col-lg-9"></div>
                        </div>
                        <div class="polsF1 disTab -spec-select-container">
                            <div class="col-lg-3">
                                <input type="hidden" class="-spec-select -spec-select-level-1" style="width: 100%">
                            </div>
                            <div class="col-lg-3">
                                <input type="hidden" class="-spec-select -spec-select-level-2" style="width: 100%">
                            </div>
                            <div class="col-lg-3">
                                <input type="hidden" class="-spec-select -spec-select-level-3" style="width: 100%">
                            </div>
                            <div class="col-lg-3">
                                 <input type="hidden" class="-spec-select -spec-select-level-4" style="width: 100%">
                            </div>

                            <input type="hidden" name="{{ form.specialization.html_name }}" value="{{ form.specialization.value }}" class="-chosen-spec-id">
                        </div>


                        <div class="searchF1">
                            <div class="col-lg-6">
                                <input
                                    type="text"
                                    name="keywords"
                                    onkeydown="event.keyCode === 13 && $(this).closest('form').submit()"
                                    value="{{ form.keywords.value }}"
                                    class="searchInp box-sizing"
                                    placeholder="Ключевые слова">
                            </div>
                            <div class="col-lg-3">
                                <a href="#" class="findReal" onclick="$(this).closest('form').submit(); return false">
                                    найти проект
                                </a>
                            </div>
                            <div class="col-lg-3">
                                <a href="{% url 'work_sell:list' %}" class="clearSearch">
                                    Очистить фильтр
                                </a>
                            </div>
                        </div>



                        <div class="resSearchF1">
                            <div class="col-lg-3">
                                <p class="titleResF1">Расширенный поиск</p>
                                <button class="resButtonF1">
                                    <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                                </button>
                            </div>
                            <div class="col-lg-9">
                                <div class="borderS1"></div>
                            </div>
                        </div>









                        <div class="slideRes disTab activeSlide">
                            <div class="titleF1 disTab">
                                <div class="col-lg-3">Классификация здания</div>
                                <div class="col-lg-3">Вид строительства</div>
                                <div class="col-lg-3"></div>
                            </div>

                            <div class="polsF1 disTab">
                                <div class="col-lg-3">
                                    {{ form.building_classification }}
                                </div>

                                <div class="col-lg-3">
                                    {{ form.construction_type }}
                                </div>
                            </div>
                        </div>





                        <div class="slideRes disTab activeSlide">
                            <div class="titleF1 disTab">
                                <div class="col-lg-3">Местоположение</div>
                            </div>

                            <div class="polsF1 disTab">
                                <div class="col-lg-3">
                                    <input type="hidden" class="-location-select -location-select-country" style="width: 100%">
                                </div>

                                <div class="col-lg-3">
                                    <input type="hidden" class="-location-select -location-select-region" style="width: 100%">
                                </div>

                                <div class="col-lg-3">
                                    <input type="hidden" class="-location-select -location-select-city" style="width: 100%">
                                </div>

                                <input type="hidden" id="chosenLocationId" name="{{ realty_form.location.html_name }}" value="{{ realty_form.location.value }}">
                            </div>


                        </div>
                    </div>
                </div>


			</form>
            
            
            <div class="galleryWork disTab">
                {% for work in work_sells %}
                    <div class="col-lg-3">
                        <div class="insetCol box-sizing disTab">
                              <a href="{% url 'work_sell:detail' work.pk %}">
                                {% thumbnail work.get_cover "265x265" crop="center" as im %}
                                    <div class="imgGal" style="background: url('{{ im.url }}') no-repeat center;">
                                        <div class="imgFigure"></div>
                                    </div>
                                {% endthumbnail %}
                            </a>
                            <div class="cenaImg box-sizing">
                                <div class="cenaImgInset">
                                    {{ work.budget }}<i class="{% fa_currency_classes work.currency %}"></i>
                                </div>
                            </div>
                        </div>
                        <div class="insetCol2 box-sizing disTab">
                            <a href="{% url 'work_sell:detail' work.pk %}">{{ work }}</a>
                            {% if request.user.pk == work.contractor.pk %}
                            <div class="buttonsImg" disTab>
                                <a href="{% url 'work_sell:edit' work.pk %}">
                                   <div class="insetBI insetBI1">
                                       <i class="fa fa-pencil"></i>
                                   </div>
                                </a>
                                <a href="{% url 'work_sell:delete' work.pk %}">
                                <div class="insetBI insetBI2">
                                    <i class="fa fa-times"></i>
                                </div>
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            
            
            <div class="col-lg-12 pagin">
                {% include 'partials/pagination.html' %}	
            </div>
            
            
            {% include 'partials/footer.html' %}
        </div>
    </div>
{% endblock %}