api/urls.py
from rest_framework import routers
from django.conf.urls import url, include

from .views import (
    AnswerViewSet,
    ContractorResumeFilesViewSet,
    ContractorResumeViewSet,
    DocumentViewSet,
    ElFormatViewSet,
    LocationViewSet,
    LocationViewSetFlat,
    MessageViewSet,
    NoteViewSet,
    OrderViewSet,
    PortfolioPhotoViewSet,
    PortfolioViewSet,
    ProjectViewSet,
    RealtyViewSet,
    UpdateRealty,
    ReviewViewSet,
    BuildingClassificationViewSet,
    SpecializationViewSet,
    SpecializationViewSetFlat,
    ConstructionTypeViewSet,
    StageViewSet,
    StageUpdateViewSet,
    TeamViewSet,
    UserViewSet,
    WorkSellPhotoViewSet,
    WorkSellViewSet,
)

router = routers.DefaultRouter()

router.register(r'answers', AnswerViewSet)
router.register(r'building_classifications', BuildingClassificationViewSet)
router.register(r'construction_type', ConstructionTypeViewSet)
router.register(r'contractorresume', ContractorResumeViewSet)
router.register(r'contractorresumefiles', ContractorResumeFilesViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'el_format', ElFormatViewSet)
router.register(r'locations', LocationViewSet)
router.register(r'locations_flat', LocationViewSetFlat)
router.register(r'message', MessageViewSet, base_name='Message')
router.register(r'note', NoteViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'portfolio-photos', PortfolioPhotoViewSet)
router.register(r'portfolios', PortfolioViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'realties', RealtyViewSet)
router.register(r'reviews', ReviewViewSet)
router.register(r'specializations', SpecializationViewSet)
router.register(r'specializations_flat', SpecializationViewSetFlat)
router.register(r'stages', StageViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'users', UserViewSet)
router.register(r'work-sell-photos', WorkSellPhotoViewSet)
router.register(r'work-sells', WorkSellViewSet)

urlpatterns = router.urls

urlpatterns = [
    url(r'^update_stages/$', StageUpdateViewSet.as_view()),
    # url(r'^orders/(?P<pk>\d+)/$', OrderViewSet.as_view({'delete'})),
]

urlpatterns += router.urls

chat/urls.py
from django.conf import urls

from .views import (
    ChatUserView,
    DocumentCreateView,
    messages_delete,
    project_delete,
    download_file,
)

app_name = 'chat'

urlpatterns = [
    urls.url(r'^$', ChatUserView.as_view(), name='chat-user'),
    urls.url(r'^messages_delete/$', messages_delete, name='chat-messages_delete'),
    urls.url(r'^project/trashed/$', project_delete),
    urls.url(r'^create/$', DocumentCreateView.as_view()),
    urls.url(r'^download/(?P<file_name>.+)', download_file),

]

projects/urls.py
from django.conf import urls

from .views import (
    # ContractorOfferOrder,
    # TeamOfferOrder,
    add_candidate,
    ArbitrationCreateView,
    CandidateDeleteView,
    # contractor_portfolio_create,
    ContractorAnswerArchiveView,
    ContractorPortfolioCreateView,
    ContractorPortfolioTrashView,
    ContractorPortfolioEditView,
    CustomerOfferOrderView,
    CustomerProjectCreateView,
    CustomerProjectDeleteView,
    CustomerProjectEditView,
    CustomerProjectRestoreView,
    CustomerProjectTrashView,
    PortfolioDetail,
    ProjectAnswerCreateMessageView,
    ProjectComparisonView,
    ProjectDetailWithAnswerView,
    ProjectFilterView,
    ProjectWorkTypeSuggestionView,
    RejectProjectAnswerView,
    RestoreProjectAnswerView,
    sort_candidates,
)

app_name = 'projects'

urlpatterns = [
    urls.url(r'^$', ProjectFilterView.as_view(), name='project-filter'),

    # urls.url(r'^create/$', CustomerProjectCreateView.as_view(), name='customer-project-create'),
    urls.url(r'^create$', CustomerProjectCreateView.as_view(), name='customer-project-create'),
    urls.url(r'^(?P<pk>\d+)/$', ProjectDetailWithAnswerView.as_view(), name='detail'),
    urls.url(r'^(?P<pk>\d+)/edit/$', CustomerProjectEditView.as_view(), name='customer-project-edit'),
    urls.url(r'^(?P<pk>\d+)/trash/$', CustomerProjectTrashView.as_view(), name='customer-project-trash'),
    urls.url(r'^(?P<pk>\d+)/restore/$', CustomerProjectRestoreView.as_view(), name='customer-project-restore'),
    urls.url(r'^(?P<pk>\d+)/delete/$', CustomerProjectDeleteView.as_view(), name='customer-project-delete'),

    urls.url(r'^create-answer-message/(?P<pk>\d+)/$', ProjectAnswerCreateMessageView.as_view(),
             name='create-answer-message'),
    urls.url(r'^reject-project-answer/(?P<pk>\d+)/$', RejectProjectAnswerView.as_view(), name='reject-project-answer'),
    urls.url(r'^restore-project-answer/(?P<pk>\d+)/$', RestoreProjectAnswerView.as_view(),
             name='restore-project-answer'),

    urls.url(r'^arbitration/create/$', ArbitrationCreateView.as_view(), name='arbitration-create'),
    urls.url(r'^answer/move/archive/$', ContractorAnswerArchiveView.as_view(), name='contractor-answer-archive'),

    urls.url(r'^portfolio/create/$', ContractorPortfolioCreateView.as_view(), name='contractor-portfolio-create'),
    urls.url(r'^portfolio/(?P<pk>\d+)/$', PortfolioDetail.as_view(), name='contractor-portfolio-detail'),
    urls.url(r'^portfolio/(?P<pk>\d+)/edit/$', ContractorPortfolioEditView.as_view(),
             name='contractor-portfolio-edit'),
    urls.url(r'^portfolio/(?P<pk>\d+)/trash/$', ContractorPortfolioTrashView.as_view(),
             name='contractor-portfolio-trash'),

    urls.url(r'^candidate/add/(?P<answer_id>(\d+))/(?P<project_id>(\d+))/$', add_candidate, name='add-candidate'),
    urls.url(r'^candidate/delete/(?P<pk>(\d+))/$', CandidateDeleteView.as_view(), name='delete-candidate'),
    urls.url(r'^candidate/comparison/sort/$', sort_candidates, name='comparison-sort'),
    urls.url(r'^candidate/comparison/(?P<pk>\d+)/$', ProjectComparisonView.as_view(), name='comparison'),

    urls.url(r'^customer-offer-order/(?P<answer_id>(\d+))/(?P<project_id>(\d+))/$', CustomerOfferOrderView.as_view(),
             name='customer-offer-order'),

    urls.url(r'^suggest-work-type/$', ProjectWorkTypeSuggestionView.as_view(), name='suggest-work-type'),
]

users/urls.py
from django.conf import urls

from .views import (
    AcceptTeamInvitation,
    RefuseTeamInvitation,
    contractor_resumefile_create,
    ContractorChatProjectsView,
    ContractorFilterView,
    ContractorOfficeProjectsView,
    ContractorOfficeView,
    ContractorProfileView,
    ContractorResumeUpdateView,
    CreateTeamInvitation,
    CustomerProfileView,
    CustomerProfileCurrentProjectsView,
    CustomerProfileReviewsView,
    CustomerProfileTrashedProjectsView,
    TeamCreateView,
    TeamProfileView,
    UserProfileEditViewFull,
    dashboard_redirect
)

app_name = 'users'

urlpatterns = [
    urls.url(r'^(?P<pk>\d+)/edit/$', UserProfileEditViewFull.as_view(), name='user-profile-edit'),
    urls.url(r'^dashboard_redirect/$', dashboard_redirect, name='dashboard-redirect'),
    urls.url(r'^customers/(?P<pk>\d+)/$', CustomerProfileView.as_view(),
             name='customer-profile'),
    urls.url(r'^customers/(?P<pk>\d+)/trashed-projects/$', CustomerProfileTrashedProjectsView.as_view(),
             name='customer-profile-trashed-projects'),
    urls.url(r'^customers/(?P<pk>\d+)/current-projects/$', CustomerProfileCurrentProjectsView.as_view(),
             name='customer-profile-current-projects'),
    urls.url(r'^customers/(?P<pk>\d+)/reviews/$', CustomerProfileReviewsView.as_view(),
             name='customer-profile-reviews'),

    urls.url(r'^contractors/$', ContractorFilterView.as_view(), name='contractor-filter'),
    urls.url(r'^contractors/resume/(?P<pk>\d+)/edit/$', ContractorResumeUpdateView.as_view(),
             name='contractor-resume-update'),
    urls.url(r'^contractors/team/create/$', TeamCreateView.as_view(), name='team-create'),
    urls.url(r'^contractorsresumefiles/create/$', contractor_resumefile_create, name='contractor-resume-file-create'),
    urls.url(r'^contractors/(?P<pk>\d+)/$', ContractorProfileView.as_view(), name='contractor-profile'),
    urls.url(r'^contractor-office/$', ContractorOfficeView.as_view(), name='contractor-office'),
    urls.url(r'^contractor-office/open-projects/$', ContractorOfficeProjectsView.as_view(),
             name='contractor-office-open-projects'),
    urls.url(r'^contractor-office/work-projects/$', ContractorChatProjectsView.as_view(),
             name='contractor-office-chat-projects'),

    urls.url(r'^teams/(?P<pk>\d+)/$', TeamProfileView.as_view(), name='team-profile'),

    urls.url(r'^create-team-invitation/(?P<contractor_id>\d+)/$', CreateTeamInvitation.as_view(),
             name='create-team-invitation'),
    urls.url(r'^accept-team-invitation/(?P<owner_id>\d+)/$', AcceptTeamInvitation.as_view(),
             name='accept-team-invitation'),
    urls.url(r'^refuse-team-invitation/(?P<owner_id>\d+)/$', RefuseTeamInvitation.as_view(),
             name='refuse-team-invitation'),
]

users/templates/partials/contractor_profile_tabs.html
{% load user_tags %}


{% url 'users:contractor-office' as contractor_office_url %}
{% url 'users:contractor-office-open-projects' as contractor_office_open_projects_url %}
{% url 'users:contractor-office-chat-projects' as contractor_office_chat_projects_url %}

<div class="profileTabs">
    <ul class="nav nav-tabs nav-justified">
        <li role="presentation">
            <a href="{% url 'users:contractor-filter' %}">Поиск исполнителей</a>
        </li>
        
        <li role="presentation" {% if request.path == contractor_office_url %}class="active"{% endif %}>
            <a href="{{ contractor_office_url }}">Мои группы</a>
            <div class="roundsCount"></div>
        </li>
        
        <li role="presentation" {% if request.path == contractor_office_open_projects_url %}class="active"{% endif %}>
            <a href="{{ contractor_office_open_projects_url }}" >Открытые проекты</a>
            <span class="desPresent">в процессе обсуждения</span>
            
            <div class="roundsCount">
                <div class="countG">{% get_open_projects_grouped request.user %}</div>
            </div>
        </li>
        
        <li role="presentation" {% if request.path == contractor_office_chat_projects_url %}class="active"{% endif %}>
            <a href="{{ contractor_office_chat_projects_url }}">Проекты в работе</a>
            
            <div class="roundsCount">
                <div class="countG">{%  get_customer_chat_open_projects request.user %}</div>
            </div>
        </li>
    </ul>
</div>

users/templates/partials/inc-contractors-results.html
{% load common_tags %}
{% load specializtions_tags %}
{% load thumbnail %}
{% load i18n %}

<input id="titleScore" type="hidden" value="{{ display_msg }}">

{% for object in objects %}
    {% if object|class_name == 'Team' %}
        {% with team=object %}
            <div class="executorBlock clearfix">
                <div class="col-lg-4">
                    <a href="{% url 'users:team-profile' pk=team.pk %}" class="aLinkExe">
                        <div class="imgExecutor">
                            {% if team.owner.avatar %}
                                {% thumbnail team.owner.avatar "126x125" crop="center" as avatar %}
                                    <img src="{{ avatar.url }}" alt="profile-image">
                                {% endthumbnail %}
                            {% else %}
                                {% if team.owner.gender == "female" %}
                                    <img src="{% static 'img/avatars/avatar-female.jpg' %}" alt="profile-image">
                                {% else %}
                                    <img src="{% static 'img/avatars/avatar-male.jpg' %}" alt="profile-image">
                                {% endif %}
                            {% endif %}
                        </div>
                    </a>
                    <p class="nameExecutor">
                        <a href="{% url 'users:team-profile' pk=team.pk %}">{{ team.name }}</a>
                    </p>
                    <p class="navv2">На сайте c {{ team.created|date:"d M Y" }}</p>
                    <div class="statusUser">Свободен</div>
                </div>


                <div class="col-lg-2">
                    <ul class="listExecutor">
                        <li>
                            <a href="{% url 'users:team-profile' pk=team.pk %}">
                                смотреть профиль
                            </a>
                        </li>
                        <li>
                            {% if request.user.is_customer %}
                                <a
                                        href="#"
                                        onclick="return false"
                                        data-contractor-id="{{ team.owner.pk }}"
                                        data-team-id="{{ team.pk }}"
                                        data-is-team-offer="true"
                                        data-toggle="modal"
                                        data-target="#projectSelectionModal">
                                    предложить проект
                                </a>
                            {% endif %}
                        </li>
                        <li>
                            <a href="{% url 'chat:chat-user' %}?user_id={{ team.owner.pk }}#user{{ team.owner.pk }}">
                                написать сообщение
                            </a>
                        </li>
                    </ul>
                </div>


                <div class="col-lg-3">
                    {% specialization_team_widget team_id=team.pk %}
                </div>


                <div class="col-lg-3 retts">
                    {% ratings_team_widget team.pk 'restList2' %}

                    <!-- TODO -->
                    <div class="sroUser sroExecutor">
                        <div class="iconSRO"></div>
                        <p>Есть допуск СРО</p>
                    </div>
                </div>
                <div class="gallMini disTab">
                    {% for portf in team.portfolios.all|slice:':4' %}
                        <div class="col-lg-3">
                            <a href="#" class="linkInsetCol">
                                <div class="insetCol box-sizing disTab">
                                    <div class="imgGal"
                                         style="background-image: url('{{ portf.photos.first.img.url }}')">
                                        <div class="imgFigure"></div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endwith %}
    {% elif object|class_name == 'User' %}
        {% with contractor=object %}
            <div class="executorBlock clearfix">
                <div class="col-lg-4">
                    <a href="{% url 'users:contractor-profile' pk=contractor.pk %}" class="aLinkExe">
                        <div class="imgExecutor">
                            {% if contractor.avatar %}
                                {% thumbnail contractor.avatar "126x125" crop="center" as avatar %}
                                    <img src="{{ avatar.url }}" alt="profile-image">
                                {% endthumbnail %}
                            {% else %}
                                {% if contractor.gender == "female" %}
                                    <img src="{% static 'img/avatars/avatar-female.jpg' %}" alt="profile-image">
                                {% else %}
                                    <img src="{% static 'img/avatars/avatar-male.jpg' %}" alt="profile-image">
                                {% endif %}
                            {% endif %}
                        </div>
                    </a>
                    <p class="nameExecutor">
                        <a href="{% url 'users:contractor-profile' pk=contractor.pk %}">{{ contractor.get_full_name }}
                            [{{ contractor.username }}]</a>
                    </p>
                    <p class="navv2">На сайте c {{ contractor.created|date:"d M Y" }}</p>

                    {% if contractor.contractor_status == 'free' %}
                        <div class="statusUser">Свободен</div>
                    {% else %}
                        <div class="statusUser busy">Занят</div>
                    {% endif %}
                </div>


                <div class="col-lg-2">
                    <ul class="listExecutor">
                        <li>
                            <a href="{% url 'users:contractor-profile' pk=contractor.pk %}">
                                смотреть профиль
                            </a>
                        </li>

                        {% if request.user.is_customer %}
                            <li>
                                <a
                                        href="#"
                                        onclick="return false"
                                        data-contractor-id="{{ contractor.pk }}"
                                        data-toggle="modal"
                                        data-target="#projectSelectionModal">
                                    предложить проект
                                </a>
                            </li>
                        {% endif %}

                        <li>
                            <a href="{% url 'chat:chat-user' %}?user_id={{ contractor.pk }}#user{{ contractor.pk }}">
                                написать сообщение
                            </a>
                        </li>
                    </ul>
                </div>


                <div class="col-lg-3">
                    {% specialization_widget user_id=contractor.pk %}
                </div>


                <div class="col-lg-3 retts">
                    {% ratings_widget contractor.pk 'restList2' %}

                    {% if contractor.cro %}
                        <div class="sroUser sroExecutor">
                            <div class="iconSRO"></div>
                            <p>Есть допуск СРО</p>
                        </div>
                    {% endif %}
                </div>
                <div class="gallMini disTab">
                    {% for portf in contractor.portfolios.all|slice:':4' %}
                        <div class="col-lg-3">
                            <a href="#" class="linkInsetCol">
                                <div class="insetCol box-sizing disTab">
                                    <div class="imgGal"
                                         style="background-image: url('{{ portf.photos.first.img.url }}')">
                                        <div class="imgFigure"></div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endwith %}
    {% endif %}
{% endfor %}
<div class="row">
    <div class="col-lg-12 pagin">
        {% include 'partials/ajax_pagination.html' %}
    </div>
</div>

users/templates/partials/inc-customer_profile-info.html
{% load thumbnail %}
{% load staticfiles %}
{% load specializtions_tags %}
{% load user_tags %}
<div class="row mod-row-eq-height" style="position: relative">
    <div class="col-lg-3">
        <div class="avatar">
            {% if customer.avatar %}
                {% thumbnail customer.avatar "220x220" crop="center" as im %}
                    <img src="{{ im.url }}" alt="profile-image">
                {% endthumbnail %}
            {% else %}
                {% if customer.gender == "female" %}
                    <img src="{% static 'img/avatars/avatar-female.jpg' %}" alt="profile-image">
                {% else %}
                    <img src="{% static 'img/avatars/avatar-male.jpg' %}" alt="profile-image">
                {% endif %}
            {% endif %}
        </div>
        <div class="old-main">
            <div class="menuUser disTab">
                <ul style="margin-bottom: 0; padding-left: 0">
                    {% if customer.pk != request.user.pk %}
                        <li class="icon_um3">
                            <a href="{% url 'chat:chat-user' %}?user_id={{ customer.pk }}#user{{ customer.pk }}">
                                написать сообщение
                            </a>
                            <span></span>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="row mod-row-eq-height">
            <div class="col-lg-5">
                <span class="user_name">{{ customer.get_full_name }} <br>[{{ customer.username }}]</span>
                <table style="margin-top: 10px; margin-bottom: 10px">
                    <tr>
                        <td style="min-width: 100px">На сайте:</td>
                        <td>{{ on_site }}</td>
                    </tr>
                    <tr>
                        <td>Страна:</td>
                        <td>{{ customer.country }}</td>
                    </tr>
                    <tr>
                        <td>Город:</td>
                        <td>{{ customer.city }}</td>
                    </tr>
                </table>
                {% if request.user == customer %}
                    <a href="{% url 'users:user-profile-edit' pk=pk %}" class="btn btn-simple mod-align-center-inline"
                       style="padding: 8px 20px; font-size: 11pt; letter-spacing: 1px">
                        <span type="submit" class="icon-edit"> </span> редактировать профиль
                    </a>
                {% endif %}
            </div>

            <div class="col-lg-7"
                 style="border-bottom: 1px solid gainsboro; border-top: 1px solid gainsboro; position: relative">
                {% if request.user.is_authenticated %}
                    <a href="#" data-toggle="modal" data-target="#contact-customer-modal"
                       class="icon-contacts"
                       style="position: absolute;top: 20px;left: 5px;">
                        Показать контакты
                    </a>
                {% endif %}
                <table class="ratings" style="float: right; margin-top: 7px; border-left: 1px solid #dcdcdc">
                    <tr>
                        <td>
                            <div class="icon-rating">Рейтинг:</div>
                        </td>
                        <td>
                            <span> {{ ratings }}</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="icon-deals">Безопасные сделки:</div>
                        </td>
                        <td>
                            <span> {{ deals }}</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="icon-reviews">Отзывы:</div>
                        </td>
                        <td style="letter-spacing: 4px">
                            <span class="positive">  {{ reviews_p }}</span>
                            <span class="neutral"> {{ reviews_n }}</span>
                            <span class="negative">  {{ reviews_m }}</span>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row" style="position: absolute;bottom: 0">
            <div class="col-lg-12">
                <div class="tabs">
                    <ul class="nav nav-tabs nav-justified">
                        {% if request.user == customer %}
                            <li class="active">
                                <a data-toggle="tab" href="#objects">
                                    <div class="mod-align-center-inline"> Объекты <span
                                            class="count">{{ objects.count }}</span></div>
                                </a>
                            </li>
                        {% endif %}
                        <li class="{% if request.user != customer %}active{% endif %}">
                            <a data-toggle="tab" href="#open_projects">
                                <div class="mod-align-center-inline"> Открытые заказы <span
                                        class="count">{{ open_projects.count }}</span></div>
                            </a>
                        </li>
                        {% if request.user == customer %}
                            <li>
                                <a data-toggle="tab" href="#in_work_projects">
                                    <div class="mod-align-center-inline"> Заказы в работе <span
                                            class="count">{{ projects_in_work.count }}</span></div>
                                </a>
                            </li>
                        {% endif %}
                        <li>
                            <a data-toggle="tab" href="#rewiews">
                                <div class="mod-align-center-inline"> Отзывы <span
                                        class="count">{{ reviews.count }}</span></div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/partials/inc-projects.html
{% load project_tags thumbnail%}
<div class="projectsBlock new-pro-block disTab">
    {% for proj in open_projects %}
        <div class="projectPro clearfix">
            <div class="col-lg-9 leftPro">
                <p class="titlePro">
                    <a href="{% url 'projects:detail' proj.pk %}">{{ proj.name }}</a>
                </p>

                <ul class="desPro">
                    <li>Объект "{{ proj.realty.name }}"</li>
                    <li><span>{{ proj.get_team_answers|length }}</span> ответ от имени
                        группы
                    </li>
                </ul>

                {% if request.user == customer %}
                    <ul class="color-menu">
                        <li>
                            <a href="{% url 'projects:detail' proj.pk %}#new-answers">Новые: {{ proj|get_new_answers|length }}</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:detail' proj.pk %}#candidate-answers">Кандидаты: {{ proj|get_candidate_answers|length }}</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:detail' proj.pk %}#rejected-answers">Отказал: {{ proj|get_rejected_answers|length }}</a>
                        </li>
                    </ul>
                {% endif %}

                <p class="textPro">
                    {{ proj.text }}
                </p>

                <ul class="listPro listPro_srch-style">
                    <li class="listPro__author">
                        {% thumbnail customer.avatar "35x35" crop="center" as avatar %}
                            <img src="{{ avatar.url }}" width="{{ avatar.width }}" height="{{ avatar.height }}">
                        {% endthumbnail %}
                        <span>{{ customer.get_full_name }}</span>
                    </li>
                    <li class="listPro__date"><span>{{ proj.created }}</span></li>
                    <li class="listPro__hits"><span>{{ proj.hit_count.hits }}</span></li>
                    <li class="listPro__count"><span>{{ proj.answers.count }}</span></li>
                </ul>
            </div>

            <div class="col-lg-3 rightPro right-pro-red">
                <p class="cenaPro">
                    {{ proj.budget }} <i
                        class="{% fa_currency_classes proj.currency %}"></i>
                </p>

                {% if request.user == proj.customer %}
                    {% if trash %}
                        <ul>
                            <li class="icon-restore">
                                <form action="{% url 'projects:customer-project-restore' pk=proj.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">

                                    <a href='#' onclick="$(this).closest('form').submit(); return false">
                                        Восстановить из корзины
                                    </a>
                                </form>
                            </li>

                            <li>
                                <form action="{% url 'projects:customer-project-delete' pk=proj.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">

                                    <a href='#' onclick="$(this).closest('form').submit(); return false">
                                        Удалить навсегда
                                    </a>
                                </form>
                            </li>
                        </ul>
                    {% else %}
                        <ul>
                            <li {% if not proj.secure_deal %}hidden{% endif %}>
                                Безопасная сделка
                            </li>
                            <li class="icon-edit_list">
                                <a href='{% url 'projects:customer-project-edit' pk=proj.pk %}?back={{ request.path }}'>Редактировать</a>
                            </li>

                            <li>
                                <form action="{% url 'projects:customer-project-trash' pk=proj.pk %}"
                                      method="POST" novalidate>
                                    {% csrf_token %}
                                    <input type="hidden" name="next"
                                           value="{{ request.path }}">
                                    <a href="#"
                                       onclick="$(this).closest('form').submit(); return false">
                                        Переместитьв корзину
                                    </a>
                                </form>
                            </li>
                        </ul>
                    {% endif %}

                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
<div class="col-lg-12 pagin">
    {% include 'partials/pagination.html' %}
</div>